### ISSUE TITLE
Fix internal API writing to ReadOnlySpans

### ISSUE THREAD

**Issue by TimonLukas** [badcel/HidApi.Net#103]
(follow-up from https://github.com/badcel/HidApi.Net/issues/101#issuecomment-2282892674)

Currently, the [internal API of NativeMethods](https://github.com/badcel/HidApi.Net/blob/9700ffecb08932fdf26ca3baf798bb0f253c7c1d/src/HidApi.Net/Internal/NativeMethods.cs#L55-L93) takes `ReadOnlySpan` parameters, and writes to them. This is undefined behavior and can lead to bugs/errors. Everything works as of now since you're only calling it from sites following a pattern where `Span`s would be equivalent, but new/different calls could lead to unpredictable behavior.

This could be fixed by changing the implementations in `NativeMethods` like in this example:

```diff
- public static int GetFeatureReport(DeviceSafeHandle device, ReadOnlySpan<byte> data)
+ public static int GetFeatureReport(DeviceSafeHandle device, Span<byte> data)
  {
      return GetFeatureReport(device, ref MemoryMarshal.GetReference(data), (nuint) data.Length);
  }
```

And the implementations in `Device` like this:

```diff
  public ReadOnlySpan<byte> GetFeatureReport(byte reportId, int maxLength)
  {
      if (maxLength < 1)
          throw new ArgumentOutOfRangeException(nameof(maxLength), maxLength, "Please provide a value greater than 1");
      var data = new byte[maxLength];
      data[0] = reportId;
-     ReadOnlySpan<byte> spanData = data;
+     Span<byte> spanData = data;
      var result = NativeMethods.GetFeatureReport(handle, spanData);
      if (result == -1)
          HidException.Throw(handle);
      return spanData[..result];
  }
```

This way the type checker will notice writes to potentially dangerous `ReadOnlySpan`s, without affecting the current API or behavior :)

What do you think?

**Comment by badcel** [comment]
From my point of view the code is fine. I see no bug or potential bug.

I don’t understand what you mean with this: “ This way the type checker will notice writes to potentially dangerous ReadOnlySpans”

Some memory is allocated and stored in a variable which describes its content as a pointer with a length. The content of this variable can’t be changed via its underlying type as it just don’t have the necessary methods. I pass this variable on to native code as a pointer and a length. The native code fills the memory. In the end the variable is returned to the user.

I don’t see why allocating a Span makes any difference?

can you give a concrete sample where there would be a problem?

**Comment by TimonLukas** [comment]
A problem will occur if a `ReadOnlySpan` is passed in that is expected to be read-only. For example, if you decided to add overloads to the other `Get` functions, but kept them as `ReadOnlySpan`s, calling them would result in invalid behavior, which the compiler would warn about if `Span` was used instead.

Additionally (although very unlikely), this could potentially break due to new/different optimizations in the compiler. The code is creating a zero-filled array that's supposed to be read-only, and it's not calling an unsafe operation, so it could be valid to optimize such that attempting a write leads to crashes or unpredictable behavior.

Are you using `ReadOnlySpan` instead of `Span` to improve performance here? Or is there some other advantage to the current implementation? I couldn't find any information about this approach, so I'm assuming the type conversion is optimized away enough that it doesn't matter.

**Comment by badcel** [comment]
There is no advantage to this approach. I agree that it is a bit mysterious to pass an empty `ReadOnlySpan` to some method and afterwards it is filled. This code is probably misleading for contributors. When developing this code I did not see this aspect of it.

You mean the compiler would error out if I try to convert a `ReadOnlySpan` to a regular `Span`?

In regard to "Spans" in general you can treat them a little bit like an interface. They promise to provide you some valid memory address and the size of this memory block which is safe to access.

On this level it does not matter if you have the read only `Span` variant or not. It's just a pointer. The access regulation got lost. So the compiler can't optimize anything because behind the "Span interface" and its pointer there is some actual memory hidden.

For example a `new byte[8]` (on the heap) or some memory on the stack (`stackalloc byte[8]`). The user of the span does not know what kind of memory it is. Just how big it is and which area is allowed to be accessed.

So what should the compiler optimize? Spans do not allocate anything, they point to existing things.

This implementation avoids some CPU cycles because no new "Span" must be created as we would need two different instances.

**Comment by TimonLukas** [comment]
If your only reason for this implementation is optimization, I really think you don't need it - both compile to the [same assembly](https://godbolt.org/z/scbn1Enbz):

```asm
; ReadOnlySpan<byte> buffer = new byte[1024]; return buffer;
Program:GetReadOnlySpanDirect():System.ReadOnlySpan`1[ubyte] (FullOpts):
G_M34647_IG01:  ;; offset=0x0000
       push     rbp
       mov      rbp, rsp
G_M34647_IG02:  ;; offset=0x0004
       mov      rdi, 0x7D047B634180      ; ubyte[]
       mov      esi, 0x400
       call     CORINFO_HELP_NEWARR_1_VC
       add      rax, 16
       mov      edx, 0x400
G_M34647_IG03:  ;; offset=0x0021
       pop      rbp
       ret      

; Span<byte> buffer = new byte[1024]; return buffer;
Program:GetReadOnlySpanIndirect():System.ReadOnlySpan`1[ubyte] (FullOpts):
G_M53968_IG01:  ;; offset=0x0000
       push     rbp
       mov      rbp, rsp
G_M53968_IG02:  ;; offset=0x0004
       mov      rdi, 0x7D047B634180      ; ubyte[]
       mov      esi, 0x400
       call     CORINFO_HELP_NEWARR_1_VC
       add      rax, 16
       mov      edx, 0x400
G_M53968_IG03:  ;; offset=0x0021
       pop      rbp
       ret      
```

I'm certain this also holds true for JIT compiler. Since Microsoft built this API for performant operations, and they are recommending to use `ReadOnlySpan`s instead of `Span`s for common operations like logging, this would probably be addressed somewhere in their usage guidelines.

**Comment by badcel** [comment]
Ah I did not know that it is this highly optimized. Additionally your thought that it is not only important for the reader of code but even for the compiler to use an appropriate type makes a lot of sense.

I learned something new the last days, thank you!

From a coding style point of view I would tend to something like this:

```csharp
public ReadOnlySpan<byte> GetFeatureReport(byte reportId, int maxLength)
{
    if (maxLength < 1)
        throw new ArgumentOutOfRangeException(nameof(maxLength), maxLength, "Please provide a value greater than 1");

    var data = new Span<byte>(new byte[maxLength]);
    data[0] = reportId;
    var result = NativeMethods.GetFeatureReport(handle, data);

    if (result == -1)
        HidException.Throw(handle);

    return data[..result];
}
```

What do you think, this makes the code a little more compact. If you agree feel free to create a PR. :rocket:

**Comment by badcel** [comment]
I think your view on the things is absolutely right. This project is more of a side project for me, but this is the same reason I want to have it as clean and expressive as possible: To avoid bugs and unhappy users.

If you are interested in improving this code base even more, it is very welcome. I would even dare to mention that I split out part of HidApi.Net in a separate library called [WcharT.Net](https://github.com/badcel/WCharT.Net). I thought it might be of use for other interop projects even if it is relatively small. If you are interested I would welcome any feedback on this project, too. Especially as it is not at the same quality level as HidApi.Net. It improved a lot since the original code in HidApi.Net but I'm not even sure it works in 100% of the cases.

This library is probably one of the bigger reason why HidApi is cross platform in comparison to the other competing nugets.

Let's end this comment with a big thank you for all the time you already invested into this project.

**Comment by badcel** [comment]
@TimonLukas Do you plan on contributing more before you would need a new release of HidApi.Net?

**Comment by TimonLukas** [comment]
@badcel I won't be able to spend more time on this in the next few weeks sadly. So I'd suggest that you create the release, and potential improvements are left for the future - there shouldn't be a need to hard break with the API that I'm aware of right now :) thank you!
